### ISSUE TITLE
No Left handed LAYOUT in QMK

### ISSUE THREAD

**Issue by vryken** [duckyb/eternal-keypad#7]
I was trying to make a custom keymap for the Lefty config on the eternal keypad. The basic lefty firmware will not work for my needs. Anywhere  I can get a lefty LAYOUT? Keymap.c for lefty is still in the default config and QMK Configurator and VIA are as well. Any thoughts? Thanks in advance. Sadly, everything is soldered already so to flip it would be a massive pain.

**Comment by duckyb** [comment]
The layout is configured for people that use the keymap with their left hand and mouse with the right.
However, you can still configure and flash keymaps based on this layout on the lefty keypad.

When configuring the firmware, simply consider that everything will be mirrored on your device.

**Comment by vryken** [comment]
Thanks! I made some solder mistakes so have to buy another board but really like the format. Appreciate all the work on it.

**Comment by duckyb** [comment]
@vryken are you sure that you can't fix it? Contact me on discord if you need some help with it
